# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1346, 783)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1341, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.LinTab = QtWidgets.QWidget()
        self.LinTab.setObjectName("LinTab")
        self.ResetButtonLin = QtWidgets.QPushButton(self.LinTab)
        self.ResetButtonLin.setGeometry(QtCore.QRect(520, 590, 93, 28))
        self.ResetButtonLin.setObjectName("ResetButtonLin")
        self.TreshButtonLin = QtWidgets.QPushButton(self.LinTab)
        self.TreshButtonLin.setGeometry(QtCore.QRect(640, 590, 131, 28))
        self.TreshButtonLin.setObjectName("TreshButtonLin")
        self.label = QtWidgets.QLabel(self.LinTab)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.LinTab)
        self.label_2.setGeometry(QtCore.QRect(790, 30, 151, 41))
        self.label_2.setObjectName("label_2")
        self.DistanceLabel = QtWidgets.QLabel(self.LinTab)
        self.DistanceLabel.setGeometry(QtCore.QRect(230, 30, 151, 41))
        self.DistanceLabel.setObjectName("DistanceLabel")
        self.UnitLabel = QtWidgets.QLabel(self.LinTab)
        self.UnitLabel.setGeometry(QtCore.QRect(290, 30, 151, 41))
        self.UnitLabel.setObjectName("UnitLabel")
        self.VoltageLabel = QtWidgets.QLabel(self.LinTab)
        self.VoltageLabel.setGeometry(QtCore.QRect(930, 30, 151, 41))
        self.VoltageLabel.setObjectName("VoltageLabel")
        self.LinVoltageGraph = QtWidgets.QGraphicsView(self.LinTab)
        self.LinVoltageGraph.setGeometry(QtCore.QRect(665, 80, 581, 451))
        self.LinVoltageGraph.setObjectName("LinVoltageGraph")
        self.LinDistGraph = QtWidgets.QGraphicsView(self.LinTab)
        self.LinDistGraph.setGeometry(QtCore.QRect(30, 80, 591, 451))
        self.LinDistGraph.setObjectName("LinDistGraph")
        self.tabWidget.addTab(self.LinTab, "")
        self.RotTab = QtWidgets.QWidget()
        self.RotTab.setObjectName("RotTab")
        self.ResetButtonRot = QtWidgets.QPushButton(self.RotTab)
        self.ResetButtonRot.setGeometry(QtCore.QRect(20, 690, 93, 28))
        self.ResetButtonRot.setObjectName("ResetButtonRot")
        self.TreshButtonRot = QtWidgets.QPushButton(self.RotTab)
        self.TreshButtonRot.setGeometry(QtCore.QRect(140, 690, 131, 28))
        self.TreshButtonRot.setObjectName("TreshButtonRot")
        self.label_3 = QtWidgets.QLabel(self.RotTab)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 151, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.RotTab)
        self.label_4.setGeometry(QtCore.QRect(20, 460, 151, 41))
        self.label_4.setObjectName("label_4")
        self.WheelInput = QtWidgets.QLineEdit(self.RotTab)
        self.WheelInput.setGeometry(QtCore.QRect(920, 450, 151, 51))
        self.WheelInput.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.WheelInput.setObjectName("WheelInput")
        self.label_5 = QtWidgets.QLabel(self.RotTab)
        self.label_5.setGeometry(QtCore.QRect(740, 460, 151, 41))
        self.label_5.setObjectName("label_5")
        self.DistanceLabelRot = QtWidgets.QLabel(self.RotTab)
        self.DistanceLabelRot.setGeometry(QtCore.QRect(220, 460, 151, 41))
        self.DistanceLabelRot.setObjectName("DistanceLabelRot")
        self.RotCountLabel = QtWidgets.QLabel(self.RotTab)
        self.RotCountLabel.setGeometry(QtCore.QRect(250, 40, 151, 41))
        self.RotCountLabel.setObjectName("RotCountLabel")
        self.RotGraph = QtWidgets.QGraphicsView(self.RotTab)
        self.RotGraph.setGeometry(QtCore.QRect(50, 90, 1191, 341))
        self.RotGraph.setObjectName("RotGraph")
        self.tabWidget.addTab(self.RotTab, "")
        self.VFDControlTab = QtWidgets.QWidget()
        self.VFDControlTab.setObjectName("VFDControlTab")
        self.Demo_graph = QtWidgets.QGraphicsView(self.VFDControlTab)
        self.Demo_graph.setGeometry(QtCore.QRect(300, 100, 500, 461))
        # self.Demo_graph.setGeometry(QtCore.QRect(40, 20, 800, 800))
        self.Demo_graph.setObjectName("Demo_graph")
        self.pushButton = QtWidgets.QPushButton(self.VFDControlTab)
        self.pushButton.setGeometry(QtCore.QRect(110, 517, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.VFDControlTab, "")
        self.VFDMonitorTab = QtWidgets.QWidget()
        self.VFDMonitorTab.setObjectName("VFDMonitorTab")
        self.ResetButtonVFD = QtWidgets.QPushButton(self.VFDMonitorTab)
        self.ResetButtonVFD.setGeometry(QtCore.QRect(590, 650, 93, 28))
        self.ResetButtonVFD.setObjectName("ResetButtonVFD")
        self.TreshButtonVFD = QtWidgets.QPushButton(self.VFDMonitorTab)
        self.TreshButtonVFD.setGeometry(QtCore.QRect(710, 650, 131, 28))
        self.TreshButtonVFD.setObjectName("TreshButtonVFD")
        self.label_8 = QtWidgets.QLabel(self.VFDMonitorTab)
        self.label_8.setGeometry(QtCore.QRect(490, 20, 151, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.VFDMonitorTab)
        self.label_9.setGeometry(QtCore.QRect(990, 20, 151, 41))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.VFDMonitorTab)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.label_7.setObjectName("label_7")
        self.StartStopButton = QtWidgets.QPushButton(self.VFDMonitorTab)
        self.StartStopButton.setGeometry(QtCore.QRect(630, 550, 141, 28))
        self.StartStopButton.setObjectName("StartStopButton")
        self.ChangeFreq = QtWidgets.QPushButton(self.VFDMonitorTab)
        self.ChangeFreq.setGeometry(QtCore.QRect(430, 550, 93, 28))
        self.ChangeFreq.setObjectName("ChangeFreq")
        self.ResetDefaultVFD = QtWidgets.QPushButton(self.VFDMonitorTab)
        self.ResetDefaultVFD.setGeometry(QtCore.QRect(830, 550, 111, 28))
        self.ResetDefaultVFD.setObjectName("ResetDefaultVFD")
        self.FreqLabelV = QtWidgets.QLabel(self.VFDMonitorTab)
        self.FreqLabelV.setGeometry(QtCore.QRect(160, 20, 151, 41))
        self.FreqLabelV.setObjectName("FreqLabelV")
        self.CurLabelV = QtWidgets.QLabel(self.VFDMonitorTab)
        self.CurLabelV.setGeometry(QtCore.QRect(660, 20, 151, 40))
        self.CurLabelV.setObjectName("CurLabelV")
        self.VolLabelV = QtWidgets.QLabel(self.VFDMonitorTab)
        self.VolLabelV.setGeometry(QtCore.QRect(1100, 20, 151, 41))
        self.VolLabelV.setObjectName("VolLabelV")
        self.FreqGraph = QtWidgets.QGraphicsView(self.VFDMonitorTab)
        self.FreqGraph.setGeometry(QtCore.QRect(20, 80, 421, 431))
        self.FreqGraph.setObjectName("FreqGraph")
        self.VoltageGraph = QtWidgets.QGraphicsView(self.VFDMonitorTab)
        self.VoltageGraph.setGeometry(QtCore.QRect(900, 80, 421, 431))
        self.VoltageGraph.setObjectName("VoltageGraph")
        self.CurrentGraph = QtWidgets.QGraphicsView(self.VFDMonitorTab)
        self.CurrentGraph.setGeometry(QtCore.QRect(460, 80, 421, 431))
        self.CurrentGraph.setObjectName("CurrentGraph")
        self.tabWidget.addTab(self.VFDMonitorTab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Control Panel V 0.1"))
        self.ResetButtonLin.setText(_translate("Dialog", "Reset readings"))
        self.TreshButtonLin.setText(_translate("Dialog", "change treshold"))
        self.label.setText(_translate("Dialog", "Distance value"))
        self.label_2.setText(_translate("Dialog", "Actual voltage"))
        self.DistanceLabel.setText(_translate("Dialog", "0"))
        self.UnitLabel.setText(_translate("Dialog", "ft"))
        self.VoltageLabel.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LinTab), _translate("Dialog", "Liner Encoder "))
        self.ResetButtonRot.setText(_translate("Dialog", "Reset readings"))
        self.TreshButtonRot.setText(_translate("Dialog", "change treshold"))
        self.label_3.setText(_translate("Dialog", "Rotations"))
        self.label_4.setText(_translate("Dialog", "Distance:"))
        self.WheelInput.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "Wheel Diameter:"))
        self.DistanceLabelRot.setText(_translate("Dialog", "0"))
        self.RotCountLabel.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RotTab), _translate("Dialog", "Rotary Encoder"))
        self.pushButton.setText(_translate("Dialog", "Clear demo graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VFDControlTab), _translate("Dialog", "VFD controls"))
        self.ResetButtonVFD.setText(_translate("Dialog", "Reset readings"))
        self.TreshButtonVFD.setText(_translate("Dialog", "change treshold"))
        self.label_8.setText(_translate("Dialog", "Current:"))
        self.label_9.setText(_translate("Dialog", "Voltage"))
        self.label_7.setText(_translate("Dialog", "Frequency:"))
        self.StartStopButton.setText(_translate("Dialog", "Start/Stop mortor"))
        self.ChangeFreq.setText(_translate("Dialog", "Change freq"))
        self.ResetDefaultVFD.setText(_translate("Dialog", "reset to default"))
        self.FreqLabelV.setText(_translate("Dialog", "0"))
        self.CurLabelV.setText(_translate("Dialog", "0"))
        self.VolLabelV.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VFDMonitorTab), _translate("Dialog", "VFD monitoring"))
